name: run belcourt spider

on:
  schedule:
    - cron: '0 10 * * *' # daily at 10:00 (which should be 5am Nashville time?)
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner
      
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: inkyenv
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false
          auto-update-conda: true
      
      - name: check conda
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
     
      - name: execute spider script # run showtimes.py
        run: |
          cd belcourt/belcourt/spiders
          scrapy runspider showtimes.py
          scrapy runspider showtimes.py -O ../../output_showtimes.json

      - name: generate jpg # run belcourt_generate_image.py
        run: |
          cd belcourt
          python belcourt_generate_image.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Ran belcourt spider" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 